// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARHpZ68wJAYRKLns5ltQaGju7Q22FpR90',
    appId: '1:971467317926:android:bcc6749841107220af8a67',
    messagingSenderId: '971467317926',
    projectId: 'buzzchat-83810',
    storageBucket: 'buzzchat-83810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaQwhuXkah9ar5SwQI6ZoRwJulqyflJbc',
    appId: '1:971467317926:ios:0834372ac4283f94af8a67',
    messagingSenderId: '971467317926',
    projectId: 'buzzchat-83810',
    storageBucket: 'buzzchat-83810.appspot.com',
    androidClientId: '971467317926-1i424cdot3hi57bf4s5ok3epv5phk4dl.apps.googleusercontent.com',
    iosClientId: '971467317926-qb6a90b1qeolkcam1jegqku3vsutr7d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}